- name: Install and Start services
  hosts: localhost
  become: yes

  tasks:
  - name: Installing NGINX
    apt:
      name: nginx
      state: present
  - name: Starting NGINX service
    service:
      name: nginx
      state: started 
      enabled: true